[[SeisSol]]
arch = "aarch64"
git-tree-sha1 = "9ce416d6990a6b8ee515084f9505ed501960f945"
mpi = "mpiabi"
os = "macos"

    [[SeisSol.download]]
    sha256 = "a411f2033d25a6eecc4e1097bf142c5fe98e426e8c66b74a850403db7f9ca0ff"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "aarch64"
git-tree-sha1 = "0df137813a21064e2e506fcde296419f7fd84cca"
mpi = "mpich"
os = "macos"

    [[SeisSol.download]]
    sha256 = "48e7050d494468be8a65e14606045940fbacb4f115dedf2842d34744ab120b4d"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "aarch64"
git-tree-sha1 = "dc4f77abc712211b70c1c2a89e84b90ea9e81721"
mpi = "mpitrampoline"
os = "macos"

    [[SeisSol.download]]
    sha256 = "1768043a0c27fb9c250ef9e56c86454588401e17aa06608676dee5053287e172"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SeisSol]]
arch = "aarch64"
git-tree-sha1 = "27983130a7b4386b58bc514b5aaad249208e94bc"
mpi = "openmpi"
os = "macos"

    [[SeisSol.download]]
    sha256 = "59cfcfd8b8a6c7c27aa92a4eae28ab8c527f3bf92a5035bf08b54544e8920b1b"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5154af0c93940081bd8353890eabed333eb120a6"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "bbafaf5929c09e350d9393144c496eb8e5c296b7c75447ae0497fd62b75c12cf"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0bc21718ebffce0951b7b4e483691972b329a0c"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "9440cee145bd0b648503fb90a5d0f29a6c64293703755e8bbca7367374ce09ef"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6e4d5135a5cec2a07fb423b883b6434e6808b9b"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SeisSol.download]]
    sha256 = "9070b195dcf7cad612f279ddb051bcff61103d6ec72d4161f4bf7345ef3e2e41"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6234a420d6e6ab27d94e232690100174268e196b"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "85fd1578070bb3956064b033a61d6d45dd34d618cfc5ec557ae1c6db4a14f8c9"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adb1778fb683e2f448fc5d0b207c74a5aa124cfa"
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "1ccd637a96118ea950fb72e235d36f921f532ca5210d36efad0fd7977e9982a6"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdd82920013390016295b522d116ab728471de2d"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "fb7b32533c7bb264afe8b712b65d4d0051dfabb717f4ee41cd3dd32c2367fc66"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1cc38401a0cfa6d8dc88be00994f49e7ddb9646"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "4b5d53bb630413eeb3530acdafde13e70d91a1350aec4e4a3c1612302d51b5e3"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "x86_64"
git-tree-sha1 = "682b294e22c1eb5bcfae4ef00158c54e82257236"
mpi = "mpiabi"
os = "macos"

    [[SeisSol.download]]
    sha256 = "2d5982dd34b784aa6b25d183a77dfffccae045da3f51b9faa43baa131ea3c405"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "x86_64"
git-tree-sha1 = "249598c507d117a9c499839533c86e457b5afdfc"
mpi = "mpich"
os = "macos"

    [[SeisSol.download]]
    sha256 = "51793c30a8332ca56dfa3c9d41e5bcab871bcf572f7bf69ded0eb062721d8d79"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
git-tree-sha1 = "b84dea338e8847c8442d8b5731d0200c3e98400b"
mpi = "mpitrampoline"
os = "macos"

    [[SeisSol.download]]
    sha256 = "31138a5c8c694192397f2210f6d6cb1a2fefd868b03fd0ce281bb3595f489f48"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SeisSol]]
arch = "x86_64"
git-tree-sha1 = "0dd35c4824a5222d2a3b56c9d3300a2edabef2e0"
mpi = "openmpi"
os = "macos"

    [[SeisSol.download]]
    sha256 = "e1b659acedd8f145a2f11df95a7afd7218bab925831fd182126e4bbde6325fcd"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "351312be3f97d7385a9def93f050e1def3267b20"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "bd3870b9adf6e95b383f6efeaf902319580713d44d6daffb42811dc1000615a6"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72709dc40eb0de78bae4ff6c328a36eb3e505003"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "7140a23566408d79576a8107a718ed91fe8f7a909e6637bac82c391560ee5e48"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d602b400befa6b800b32974b2867bfbbff671b4"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SeisSol.download]]
    sha256 = "563ae1fa556c702b72963f008342bb5a0bdcbb893746eac215f10b3f807b8170"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18d1b7a1b7579e47c223d0d7d96cb73805e36b0b"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "d0fa00e00cee3a8129b71658a49d7c2a4ca0193b9124e23ecc68c1920967497b"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acf8b3c366f43ce28efd913d3161d505b61931e9"
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "f44398f0f1adbe0ab47d2f11230852bf7649f46e15c4fd15698010f21848641d"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2f1288dd32cd7ca75d56a02d101d240523f65d2"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "dbacded44e2746ca17b325d7485677444728cb54acd199647ab6e3ad6cb55625"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf17a413859c553242a9a50f34fd397296c733d4"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "712e43955419c9337c1b866215d7cc472b23934250c9dbec01076ca303e12689"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b1ad226275f61133576ea31a90cf2f7454f7fd7"
mpi = "microsoftmpi"
os = "windows"

    [[SeisSol.download]]
    sha256 = "15b03faefd01a96ea6267ad7c69590b4cba7f07af5759275052862c58e916a3b"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
