[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8325c2e1a8c95e6f5fec4da33a600cf6f21834ab"
mpi = "mpich"
os = "macos"

    [[SeisSol.download]]
    sha256 = "4eb094bed2ce80ac77608d2bc73e950056e7997d1db3cb2c47a877a105865eee"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e688ad25a0afd6f99b5926e338f1ff6ffc32a65"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "819c68a3307b6a30c9a3f47dc3918814fb506246afdc7d8c994bc0068c815224"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2d25b7302c5f2157a03ddcbb30db1ef1799c941"
mpi = "mpich"
os = "macos"

    [[SeisSol.download]]
    sha256 = "3e2133aee76affec70e32c0fd7dd13225d816f18486713285401456c3f68e31a"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e16ee20eb69574c14090793ec36ee3573898cb4"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "89252a36604e4a85bc65d0d004fbe656ad75512d4ecdf9f114720d1596e6ba1f"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9a271c0d78b0e53d5a0e63878543ea6db842f0c"
mpi = "microsoftmpi"
os = "windows"

    [[SeisSol.download]]
    sha256 = "d17306f2a760eb05baf849fed2989c743887079a8270d6d7bbce6ff72a6ecc4d"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
