[[SeisSol]]
arch = "aarch64"
git-tree-sha1 = "d097b1e0781001fa0ff7692f5262f2ca0871faab"
mpi = "mpiabi"
os = "macos"

    [[SeisSol.download]]
    sha256 = "ce42693f6758730c98a442d50af9c2c924a8818b591fe2ac57f340c776f2f3dc"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "aarch64"
git-tree-sha1 = "6cbb51a918dfe8ffa653ac70e3243acd07fcc2ad"
mpi = "mpich"
os = "macos"

    [[SeisSol.download]]
    sha256 = "b490aea33e273a9fb6b9970d7726f53a5fe5c2b376db5a5ea0c6bf033345be67"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "aarch64"
git-tree-sha1 = "2a2b6ddbf4618acf86cd2938e4724c917786a871"
mpi = "mpitrampoline"
os = "macos"

    [[SeisSol.download]]
    sha256 = "fb8f9f90b68ec4875e8b8fa6e93d45273868f457ebf79e2cff664d5e68f33bc6"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SeisSol]]
arch = "aarch64"
git-tree-sha1 = "39c519db92d54b3cfedef26089418f952a646fb9"
mpi = "openmpi"
os = "macos"

    [[SeisSol.download]]
    sha256 = "ba1e00f8efe592bdff0ae3b88f22cfbeb66b72c7c20860afab8babb233b6d79f"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd5826c78499c6c8aa122bf43230ed0e5eebe73b"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "1a54f30a2e9f1db0b95cc0eeb6e8c7a4f91855a24b0c9f97ecb139c7f2eb3fe2"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54659541313c1983c6266d6a440c05f0c67ef9c6"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "ef74bda57a31cde61df3b691ba85a911523e09b3e13152cdcc899af3d4d159c1"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f346b454953c64f417e92b6252d6afeb6510698e"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SeisSol.download]]
    sha256 = "e821b2cf21f5ca2a43851576cf0e0a3439bb04140ab7be6871537c44daf598cf"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cc26a67e41de73b63f760f7cc605c6269f5e4d3"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "a0b12e372b53a82c7954be68ce23d439c3efabfcce674b0744cede7f615638bb"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b24e32a9909487d250919db1def262c68132fad0"
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "8e6ee62555082a5ead5273de888be1eef5fd3dd0989e910cf3d214ccc186eef3"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6c5cf0de39c60fee46f9e774808ec94038df85c"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "d325e1fb31e88170c0ba6b1a63b32268d71bbb752f961fa480a0ffa83317bace"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c08e59a49ed4253244411d88aba6d9c8c74b19d"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "6651a8d22727f51353adabeb7e1a84c4c6aca380ad3fbee9fccc9b32d6835aa0"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "x86_64"
git-tree-sha1 = "7c839d23d3c1d0eadc6819e270e920cc998c2856"
mpi = "mpiabi"
os = "macos"

    [[SeisSol.download]]
    sha256 = "7c2e46097f39537aefdeac6e8fda2b139f581512209dcf1b8103c062d6abf9ff"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "x86_64"
git-tree-sha1 = "681fbb859f17717dd654d0a653888b1815261a57"
mpi = "mpich"
os = "macos"

    [[SeisSol.download]]
    sha256 = "8cb5e848f6a423509e002f8d53f99098dc2029dc9bba9f1cd82788160db07148"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
git-tree-sha1 = "3b7acd81a049cc1e60f6c690ad49c3df18dad5e7"
mpi = "mpitrampoline"
os = "macos"

    [[SeisSol.download]]
    sha256 = "ddf3acfda9da5263633fbb907d4718cd9e9a551424f73928221644b62cf74e17"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SeisSol]]
arch = "x86_64"
git-tree-sha1 = "0b712d3e5500b3e5aca9c5cc523fdd70f085416c"
mpi = "openmpi"
os = "macos"

    [[SeisSol.download]]
    sha256 = "c4380292357b757301f8d3bcecf4174cde5c3eb5b27922f6aed59e9dc1bc5914"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4277114bb5309b1e16d41299e223cd09484bdea7"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "8aff77de2cb5de6bf42ab70ff9d9102f41c237616577e6f8f24d9174873fe9ac"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f52a6e1498ab614bd89e9c52654c084da525fa0c"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "22e34008bb5b1fa57ec2528dd96aa6a3f8516cc3805a94754b18dee33e352af9"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdfc6efce24b635a1fe5125eb6f3cec6d87d6ec1"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SeisSol.download]]
    sha256 = "c2f5a46a0c37005374153bc8a473abefdbcbd83271af355a802945463055b4ac"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f60044dd01058fb4114974a96ee6de6e22261983"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "75f2540dcb6d6873b1974671940fbac4138cb8dd0c95a0c2e78b9b9b40f83bd2"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cb8d43528d20ba7c807e239331e9ab7e2368dd4"
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "7f43cd78519e4020454eca6fdb676f3c9b98b661186311d410a7c2b924df2aab"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17c57204d9f1f161d452082e849e31478f6b8d10"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SeisSol.download]]
    sha256 = "116f765479ca401a9c79d2052ae806a0caac36189ee6abcbd151c73e025e0a2e"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d4b5d94bc6a35f39ce3c2ad7b46b2b4dc5a72c0"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SeisSol.download]]
    sha256 = "086cc33be01afa212e55e5ba1f34e9b5a77d03bf37fd34d46d0a9bbccc596eae"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[SeisSol]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a76367cc3ee669588ecc1a520bd94e3957ade6d8"
mpi = "microsoftmpi"
os = "windows"

    [[SeisSol.download]]
    sha256 = "a787e04de526d7325bf26435d957c006242b0036b38816805366ea84a1b732e0"
    url = "https://github.com/boriskaus/SeisSol_jll.jl/releases/download/SeisSol-v1.3.2+0/SeisSol.v1.3.2.x86_64-w64-mingw32-cxx11-mpi+microsoftmpi.tar.gz"
