# Autogenerated wrapper script for SeisSol_jll for x86_64-apple-darwin-mpi+mpitrampoline
export seissol, seissol_proxy

using ASAGI_jll
using easi_jll
using HDF5_jll
using LLVMOpenMP_jll
using NetCDF_jll
using PARMETIS_jll
using yaml_cpp_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("SeisSol")
JLLWrappers.@declare_executable_product(seissol)
JLLWrappers.@declare_executable_product(seissol_proxy)
function __init__()
    JLLWrappers.@generate_init_header(ASAGI_jll, easi_jll, HDF5_jll, LLVMOpenMP_jll, NetCDF_jll, PARMETIS_jll, yaml_cpp_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        seissol,
        "bin/seissol",
    )

    JLLWrappers.@init_executable_product(
        seissol_proxy,
        "bin/seissol_proxy",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
