# Autogenerated wrapper script for SeisSol_jll for x86_64-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi
export seissol

using CompilerSupportLibraries_jll
using HDF5_jll
using PARMETIS_jll
using easi_jll
using yaml_cpp_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("SeisSol")
JLLWrappers.@declare_executable_product(seissol)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, HDF5_jll, PARMETIS_jll, easi_jll, yaml_cpp_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        seissol,
        "bin\\SeisSol_Release_dnoarch_4_elastic.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
