# Autogenerated wrapper script for SeisSol_jll for x86_64-w64-mingw32-cxx11-mpi+microsoftmpi
export seissol, seissol_proxy

using ASAGI_jll
using CompilerSupportLibraries_jll
using easi_jll
using HDF5_jll
using NetCDF_jll
using PARMETIS_jll
using yaml_cpp_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("SeisSol")
JLLWrappers.@declare_executable_product(seissol)
JLLWrappers.@declare_executable_product(seissol_proxy)
function __init__()
    JLLWrappers.@generate_init_header(ASAGI_jll, CompilerSupportLibraries_jll, easi_jll, HDF5_jll, NetCDF_jll, PARMETIS_jll, yaml_cpp_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        seissol,
        "bin\\seissol.exe",
    )

    JLLWrappers.@init_executable_product(
        seissol_proxy,
        "bin\\seissol_proxy.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
