# Autogenerated wrapper script for SeisSol_jll for x86_64-apple-darwin-libgfortran5-cxx11-mpi+mpich
export seissol

using LLVMOpenMP_jll
using HDF5_jll
using PARMETIS_jll
using easi_jll
using yaml_cpp_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("SeisSol")
JLLWrappers.@declare_executable_product(seissol)
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll, HDF5_jll, PARMETIS_jll, easi_jll, yaml_cpp_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        seissol,
        "bin/SeisSol_Release_dnoarch_4_elastic",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
